<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Gustav\Thesis\Block\Frontend\Maps $block */
$apiKey = $block->getGoogleMapApiKey();
?>

<script type="text/javascript">
    function initMap() {
    }
</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?= $escaper->escapeUrl($apiKey) ?>&callback=initMap" async defer></script>

<div class="map" id="map"></div>

<script type="text/javascript">
    require([
        'jquery',
        'googleMapConfig'
    ], function ($) {
        $('#map').googleMapConfig({});
    });
</script>
