<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Gustav\Thesis\Block\Frontend\Stores $block */

$categories = $block->getCategories();
?>
<div class="store-locator">
<div class="store-filters">
    <select class="category-filter">
        <option value="">All Categories</option>
        <?php foreach ($categories as $category): ?>
            <option value="<?= $escaper->escapeHtmlAttr($category->getId()) ?>">
                <?= $escaper->escapeHtml($category->getCategoryName()) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>

<div class="js-store-list"></div>
</div>

<script type="text/x-magento-init">
    {
        ".js-store-list": {
            "storeListWidget": {
                "actionUrl": "<?= $escaper->escapeUrl($block->getUrl('storelocator/frontend/storelist')) ?>",
            "pageSize": 5
        }
    }
}
</script>
